uploads = []
outputs = []

[[generated]]
id = "4Nq05mn_pxmTfN9CC-uUx"
uri = "file://artifacts/smokecraft/public/images/lounge-bg.png"
type = "image"
title = "luxury cigar lounge background"

[[generated]]
id = "9VtBbA-yxpP2vC05uatss"
uri = "file://artifacts/smokecraft/public/images/cigar.png"
type = "image"
title = "premium cigar product shot"

[[generated]]
id = "P-IZr46yyhIgfmokLIEmk"
uri = "file://artifacts/smokecraft/public/images/whiskey.png"
type = "image"
title = "generated_image"

[[generated]]
id = "9UiXYkRsCx-6ftPxVvdik"
uri = "file://artifacts/smokecraft/public/images/cigar1.png"
type = "image"
title = "generated_image"

[[generated]]
id = "kQfKILIGlpGjr6-HyfxXY"
uri = "file://artifacts/smokecraft/public/images/cigar2.png"
type = "image"
title = "generated_image"

[[generated]]
id = "fkZc57ieIsV3mTOIMJnDM"
uri = "file://artifacts/smokecraft/public/images/cigar3.png"
type = "image"
title = "generated_image"

[[generated]]
id = "ZzqyLYpunB7fNk4BCdxyn"
uri = "file://artifacts/smokecraft/public/images/cigar4.png"
type = "image"
title = "generated_image"
