/**
 * reconciliation_alerts — financial alert engine output.
 *
 * Auto-generated by reconciliation workers and the financial alert engine.
 * Manually dismissible by finance_admin / super_admin.
 *
 * Severity: critical > high > medium > low
 * Status:   open → acknowledged → resolved | dismissed
 */

import { pgTable, uuid, text, jsonb, timestamp, index } from "drizzle-orm/pg-core";

export const ALERT_SEVERITIES = ["critical", "high", "medium", "low"] as const;
export type AlertSeverity = typeof ALERT_SEVERITIES[number];

export const ALERT_STATUSES = ["open", "acknowledged", "resolved", "dismissed"] as const;
export type AlertStatus = typeof ALERT_STATUSES[number];

export const ALERT_CATEGORIES = [
  "payout_failure",
  "webhook_outage",
  "duplicate_charge",
  "dispute_spike",
  "elevated_refund_rate",
  "stale_tab",
  "orphan_payment",
  "payout_delay",
  "reconciliation_lag",
  "stale_payout",
  "fulfillment_gap",
  "revenue_anomaly",
] as const;
export type AlertCategory = typeof ALERT_CATEGORIES[number];

export const reconciliationAlertsTable = pgTable("reconciliation_alerts", {
  id:           uuid("id").primaryKey().defaultRandom(),
  venueId:      uuid("venue_id"),                 // null = platform-wide
  severity:     text("severity").notNull().$type<AlertSeverity>(),
  status:       text("status").notNull().default("open").$type<AlertStatus>(),
  category:     text("category").notNull().$type<AlertCategory>(),
  title:        text("title").notNull(),
  description:  text("description").notNull(),
  entityType:   text("entity_type"),              // "tab" | "payout_request" | "webhook" etc.
  entityId:     text("entity_id"),
  metadata:     jsonb("metadata"),
  resolvedBy:   uuid("resolved_by"),
  createdAt:    timestamp("created_at").notNull().defaultNow(),
  acknowledgedAt: timestamp("acknowledged_at"),
  resolvedAt:   timestamp("resolved_at"),
}, (t) => ({
  byStatus:   index("ra_status_idx").on(t.status),
  bySeverity: index("ra_severity_idx").on(t.severity),
  byVenue:    index("ra_venue_idx").on(t.venueId),
  byCategory: index("ra_category_idx").on(t.category),
}));

export type ReconciliationAlert       = typeof reconciliationAlertsTable.$inferSelect;
export type InsertReconciliationAlert = typeof reconciliationAlertsTable.$inferInsert;
