/**
 * server_pulse_events — BOH push notifications generated by the Pairing Engine.
 *
 * Each row represents one "Server Pulse" sent to the waitress/staff dashboard
 * when a guest finalises a draft profile. The recommended item and mastery boost
 * are stored for analytics and replay.
 */

import { pgTable, uuid, text, integer, timestamp } from "drizzle-orm/pg-core";

export const serverPulseEventsTable = pgTable("server_pulse_events", {
  id:              uuid("id").primaryKey().defaultRandom(),
  venueId:         uuid("venue_id"),
  tableId:         text("table_id"),
  guestProfileId:  uuid("guest_profile_id"),
  guestName:       text("guest_name"),
  guestLevel:      text("guest_level"),
  draftProfile:    text("draft_profile"),
  recommendedItem: text("recommended_item"),
  masteryBoost:    integer("mastery_boost").default(15),
  sentAt:          timestamp("sent_at", { withTimezone: true }).notNull().defaultNow(),
});

export type ServerPulseEvent = typeof serverPulseEventsTable.$inferSelect;
